kind: pipeline
type: ssh
name: ece482-projects
server:
  host: 111.186.59.59
  user: drone
  ssh_key:
    from_secret: ece482
steps:
- name: ci-install
  commands:
  - /usr/local/bin/ci-install
- name: repo-checks
  commands:
  - ci/runner.sh repo_checks
- name: compilation
  commands:
  - ci/runner.sh compile
- name: code-quality
  commands:
  - ci/runner.sh code_quality
- name: joj
  commands:
  - ci/runner.sh joj
- name: send-report
  commands:
  - ci/runner.sh open_issue
